[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[override]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[prune]
  go-tests = true
  unused-packages = true
